[package]
name = "egomoose/rbx-captcha"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
private = true

[server-dependencies]
Promise = "evaera/promise@4.0.0"
Sift = "csqrl/sift@0.0.6"